export const INPUTMODE_VALUES: string = "VALUES"
export const INPUTMODE_PENCILS: string = "PENCILS"
export const INPUTMODE_CENTERS: string = "CENTERS"
export const INPUTMODE_COLORS: string = "COLORS"
export const ALL_INPUTMODES = [INPUTMODE_VALUES, INPUTMODE_PENCILS, INPUTMODE_CENTERS, INPUTMODE_COLORS]